# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f848ad0ce9f2344d6582f7178ea3531fcbca8903018174767fca03d8c91efd83a4e8054f8944a77011a1dd2adb6546c92b3623eb3b5c768e2579136d87115e94

test:
  secret_key_base: 0fb8a2a48c0a062c7d6e2ba1fbd235820a38476551c2f6841529c5773d0325888032b03777a7de8007730919f2290892a23dd66d90ab6b4ddc586b93906212f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
